Repository bnb-chain/zkbnb, pull requests merged in 2022-10, with the labels that each got.

#207 feat: Replace apiserver gocache with ristretto cache
  deploy-local.sh
  deployment/docker-compose/docker-compose.sh
  deployment/helm/local-value/values.yaml
  deployment/helm/zkbnb/values.yaml
  go.mod
  go.sum
  service/apiserver/etc/server-api.yaml.example
  service/apiserver/internal/cache/mem_cache.go
  service/apiserver/internal/config/config.go
  service/apiserver/internal/svc/servicecontext.go
  service/apiserver/test/suite_test.go
Labels: ready for review

#217 committer: fix the bug when using new generated nft/account tx in the same block
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/full_exit_executor.go
  core/executor/full_exit_nft_executor.go
  core/statedb/state_cache.go
  dao/account/account.go
  dao/nft/nft.go
Labels: bug, ready for review

#214 feat: add totalAssetValue in GetAccount API response
  docs/api_reference.md
  service/apiserver/internal/logic/account/getaccountlogic.go
  service/apiserver/server.api
Labels: ready for review

#220 executor: fix full exit nft
  core/executor/full_exit_nft_executor.go
Labels: bug, ready for review

#206 core: move gas to block level
  .gitignore
  common/prove/types.go
  common/prove/witness_helper.go
  common/prove/witness_test.go
  core/executor/atomic_match_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/mint_nft_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  dao/account/account_history.go
  dao/tx/tx_detail.go
  deploy-qa.sh
  go.mod
  go.sum
  service/committer/committer/committer.go
  service/monitor/monitor/monitor.go
  service/prover/prover/prover.go
  service/witness/witness/witness.go
  tree/asset_tree_cache.go
  types/account.go
  types/constant.go
Labels: enhancement, ready for review

#218 refactor: reduce public inputs of block constraints
  go.mod
  go.sum
  service/prover/verifier_parse.py
Labels: ready for review

#219 core, dao: merge new update map for account and nft
  core/blockchain.go
  core/executor/atomic_match_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/full_exit_executor.go
  core/executor/full_exit_nft_executor.go
  core/executor/mint_nft_executor.go
  core/executor/register_zns_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  dao/account/account.go
  dao/block/block.go
  dao/nft/nft.go
  service/committer/committer/committer.go
Labels: ready for review

#215 feat: refine API error codes
  core/block_processor.go
  core/blockchain.go
  core/executor/atomic_match_executor.go
  core/executor/base_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/full_exit_executor.go
  core/executor/mint_nft_executor.go
  core/executor/register_zns_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/statedb.go
  go.mod
  go.sum
  service/apiserver/internal/logic/account/getaccountlogic.go
  service/apiserver/internal/logic/asset/getassetlogic.go
  service/apiserver/internal/logic/block/getblocklogic.go
  service/apiserver/internal/logic/info/searchlogic.go
  service/apiserver/internal/logic/nft/getaccountnftslogic.go
  service/apiserver/internal/logic/nft/getmaxofferidlogic.go
  service/apiserver/internal/logic/transaction/getaccountpendingtxslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/internal/logic/transaction/getblocktxslogic.go
  service/apiserver/internal/logic/transaction/getnextnoncelogic.go
  service/apiserver/internal/logic/transaction/gettxlogic.go
  types/code.go
Labels: ready for review

#226 feat: export toAccountIndex and toAccountName in Tx APIs
  service/apiserver/internal/logic/transaction/getaccountpendingtxslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/internal/logic/transaction/getblocktxslogic.go
  service/apiserver/internal/logic/transaction/getpendingtxslogic.go
  service/apiserver/internal/logic/transaction/gettxlogic.go
  service/apiserver/internal/logic/transaction/gettxslogic.go
  service/apiserver/internal/logic/utils/converter.go
  service/apiserver/server.api
Labels: ready for review

#228 committer: fix txDetails generation bug
  core/executor/deposit_nft_executor.go
  core/executor/full_exit_nft_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_nft_executor.go
  go.sum
  types/system.go
Labels: ready for review

#227 feat: support query account tx APIs by txType
  dao/tx/tx.go
  dao/tx/tx_pool.go
  service/apiserver/internal/logic/transaction/getaccountpendingtxslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/server.api
  service/apiserver/test/getaccountpendingtxs_test.go
  service/apiserver/test/getaccounttxs_test.go
Labels: ready for review

#230 crypto: update version of zkbnb-crypto
  go.mod
  go.sum
Labels: ready for review

#233 fix: correct witness data when gas account sending txs
  common/prove/witness_helper.go
  core/blockchain.go
  core/executor/atomic_match_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/mint_nft_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  go.sum
  service/apiserver/internal/handler/transaction/getexecutedtxshandler.go
  service/apiserver/internal/logic/transaction/getexecutedtxslogic.go
  service/apiserver/internal/logic/utils/converter.go
  service/committer/committer/committer.go
Labels: bug, enhancement, ready for review

#229 statedb tree: optimize the time of the statedb commit phase
  .github/workflows/integration-test.yml
  cmd/flags/flags.go
  cmd/zkbnb/main.go
  common/gopool/gopool.go
  common/metrics/metrics.go
  common/metrics/pprof/pprof.go
  common/metrics/prometheus/prometheus.go
  common/prove/witness_test.go
  core/blockchain.go
  core/statedb/statedb.go
  deploy-local.sh
  deployment/docker-compose/docker-compose.sh
  deployment/helm/local-value/values.yaml
  deployment/helm/zkbnb/templates/configmap.yaml
  deployment/helm/zkbnb/values.yaml
  deployment/tool/tool.sh
  go.mod
  go.sum
  service/apiserver/etc/server-api.yaml.example
  service/apiserver/internal/config/config.go
  service/apiserver/internal/svc/servicecontext.go
  service/apiserver/test/suite_test.go
  service/committer/committer/committer.go
  service/fullnode/fullnode/fullnode.go
  service/witness/config/config.go
  service/witness/witness/witness.go
  tools/recovery/internal/config/config.go
  tools/recovery/recovery.go
  tree/account_tree.go
  tree/nft_tree.go
  tree/treedb.go
  tree/util.go
Labels: ready for review

#235 fix: correct the wrong query of GetTxsTotalCount
  dao/tx/tx_pool.go
Labels: ready for review

#236 dependency: update zkbnb-crypto to v0.0.8
  go.mod
  go.sum
Labels: ready for review
