Repository bnb-chain/zkbnb, pull requests merged in 2022-09, with the labels that each got.

#136 ci: fix lint script
  .github/workflows/lint.yaml
  Makefile
  common/chain/balance_helper.go
  common/chain/pubdata_helper.go
  common/prove/witness_helper.go
  common/prove/witness_test.go
  service/apiserver/internal/fetcher/price/fetcher.go
  service/apiserver/internal/logic/block/getblocklogic.go
  service/apiserver/internal/logic/info/getgasfeelogic.go
  service/apiserver/internal/logic/info/getwithdrawgasfeelogic.go
  service/apiserver/test/getaccount_test.go
  service/apiserver/test/getaccountmempooltxs_test.go
  service/apiserver/test/getaccountnfts_test.go
  service/apiserver/test/getaccounts_test.go
  service/apiserver/test/getaccounttxs_test.go
  service/apiserver/test/getassets_test.go
  service/apiserver/test/getblock_test.go
  service/apiserver/test/getblocks_test.go
  service/apiserver/test/getblocktxs_test.go
  service/apiserver/test/getcurrentheight_test.go
  service/apiserver/test/getgasaccount_test.go
  service/apiserver/test/getgasfee_test.go
  service/apiserver/test/getgasfeeassets_test.go
  service/apiserver/test/getlayer2basicinfo_test.go
  service/apiserver/test/getlpvalue_test.go
  service/apiserver/test/getmaxofferid_test.go
  service/apiserver/test/getmempooltxs_test.go
  service/apiserver/test/getnextnonce_test.go
  service/apiserver/test/getpair_test.go
  service/apiserver/test/getpairs_test.go
  service/apiserver/test/getstatus_test.go
  service/apiserver/test/getswapamount_test.go
  service/apiserver/test/gettxbyhash_test.go
  service/apiserver/test/gettxs_test.go
  service/apiserver/test/getwithdrawgasfee_test.go
  service/apiserver/test/search_test.go
  service/apiserver/test/suite_test.go
  service/prover/prover/prover.go
  service/sender/sender/sender.go
  service/witness/witness/witness.go
Labels: ready for review

#138 fix: fix tests with snapshot postgres db
  service/apiserver/test/getpair_test.go
  service/apiserver/test/getswapamount_test.go
Labels: ready for review

#137 ci: add unit test to gitaction workflow
  .github/workflows/unit-test.yaml
  Makefile
  common/prove/witness_test.go
  service/apiserver/test/suite_test.go
Labels: ready for review

#141 ci: optimize the integration-test
  .github/workflows/integration-test.yml
  .github/workflows/issue-trigger.yml
  .gitignore
Labels: ready for review

#145 ci: use blocksize 1 to reduce the integration time
  .github/workflows/integration-test.yml
  deployment/docker-compose/docker-compose.sh
Labels: enhancement, ready for review

#146 deployment: add helm-chart scripts
  deployment/README.md
  deployment/helm/local-value/post-render.sh
  deployment/helm/local-value/values.yaml
  deployment/helm/zkbas/.helmignore
  deployment/helm/zkbas/Chart.yaml
  deployment/helm/zkbas/templates/NOTES.txt
  deployment/helm/zkbas/templates/_helpers.tpl
  deployment/helm/zkbas/templates/configmap.yaml
  deployment/helm/zkbas/templates/deployment.yaml
  deployment/helm/zkbas/templates/hpa.yaml
  deployment/helm/zkbas/templates/ingress.yaml
  deployment/helm/zkbas/templates/service.yaml
  deployment/helm/zkbas/templates/serviceaccount.yaml
  deployment/helm/zkbas/templates/tests/test-connection.yaml
  deployment/helm/zkbas/values.yaml
Labels: ready for review

#143 apiserver: enhance parameter check for some apis
  common/prove/witness_test.go
  service/apiserver/internal/fetcher/price/fetcher.go
  service/apiserver/internal/logic/account/getaccountlogic.go
  service/apiserver/internal/logic/block/getblocklogic.go
  service/apiserver/internal/logic/block/getblockslogic.go
  service/apiserver/internal/logic/info/getcurrencypricelogic.go
  service/apiserver/internal/logic/nft/getaccountnftslogic.go
  service/apiserver/internal/logic/transaction/getaccountmempooltxslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/internal/logic/transaction/getblocktxslogic.go
  service/apiserver/internal/logic/utils/validator.go
  service/apiserver/test/suite_test.go
  service/monitor/monitor/monitor_governance_blocks.go
Labels: ready for review

#144 core: add offer id check for cancel offer executor
  core/executor/cancel_offer_executor.go
Labels: enhancement, ready for review

#149 fix: handle price query when token not listed on cmc, add lp in accou…
  service/apiserver/internal/fetcher/price/fetcher.go
  service/apiserver/internal/logic/account/getaccountlogic.go
  types/code.go
Labels: bug, ready for review

#161 deployment ci: fix tool.sh and trigger update-integration-keyfile from PR branch
  .github/workflows/issue-trigger.yml
  deployment/tool/tool.sh
Labels: ready for review

#154 ci: fix integration-test.yml to support running on develop, master branch
  .github/workflows/integration-test.yml
  .github/workflows/lint.yaml
Labels: ready for review

#163 ci: skip fetching branches from PR numbers when running on develop and master branches
  .github/workflows/integration-test.yml
Labels: ready for review

#151 dao: refine methods, separate daos, remove useless codes
  common/prove/witness_test.go
  core/blockchain.go
  core/executor/create_pair_executor.go
  core/statedb/chaindb.go
  core/statedb/statedb.go
  dao/account/account.go
  dao/account/account_history.go
  dao/asset/asset.go
  dao/block/block.go
  dao/blockwitness/block_witness.go
  dao/blockwitness/constant.go
  dao/compressedblock/compressed_block.go
  dao/l1rolluptx/l1_rollup_tx.go
  dao/l1syncedblock/l1_synced_block.go
  dao/liquidity/liquidity.go
  dao/liquidity/liquidity_history.go
  dao/mempool/mempool.go
  dao/nft/nft.go
  dao/nft/nft_history.go
  dao/priorityrequest/priority_request.go
  dao/proof/proof.go
  dao/sysconfig/sysconfig.go
  dao/tx/tx.go
  dao/tx/txdetail.go
  service/apiserver/internal/fetcher/state/fetcher.go
  service/apiserver/internal/logic/account/getaccountlogic.go
  service/apiserver/internal/logic/account/getaccountslogic.go
  service/apiserver/internal/logic/asset/getassetslogic.go
  service/apiserver/internal/logic/block/getblocklogic.go
  service/apiserver/internal/logic/block/getblockslogic.go
  service/apiserver/internal/logic/block/getcurrentheightlogic.go
  service/apiserver/internal/logic/info/getcurrencypriceslogic.go
  service/apiserver/internal/logic/nft/getaccountnftslogic.go
  service/apiserver/internal/logic/pair/getpairslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/internal/logic/transaction/getmempooltxslogic.go
  service/apiserver/internal/logic/transaction/gettxslogic.go
  service/apiserver/internal/logic/transaction/sendtxlogic.go
  service/apiserver/internal/svc/servicecontext.go
  service/committer/committer/committer.go
  service/monitor/monitor/monitor.go
  service/monitor/monitor/monitor_generic_blocks.go
  service/monitor/monitor/monitor_governance_blocks.go
  service/monitor/monitor/monitor_priority_requests.go
  service/prover/prover/prover.go
  service/sender/sender/sender.go
  service/witness/witness/witness.go
  tools/dbinitializer/main.go
  tree/nft_tree.go
  types/code.go
Labels: ready for review

#165 ci: remove triggers on integration-test and issue-trigger
  .github/workflows/integration-test.yml
  .github/workflows/issue-trigger.yml
Labels: ready for review

#156 apiserver: add accout name fields for nft apis
  service/apiserver/internal/logic/nft/getaccountnftslogic.go
  service/apiserver/server.api
Labels: ready for review

#166 witness: init tree from latest witness height
  service/witness/witness/witness.go
Labels: bug, ready for review

#147 core: improve updating trees and preparing assets
  core/block_processor.go
  core/blockchain.go
  core/executor/add_liquidity_executor.go
  core/executor/atomic_match_executor.go
  core/executor/base_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/create_pair_executor.go
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/executor.go
  core/executor/full_exit_executor.go
  core/executor/full_exit_nft_executor.go
  core/executor/mint_nft_executor.go
  core/executor/register_zns_executor.go
  core/executor/remove_liquidity_executor.go
  core/executor/swap_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/update_pair_rate_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  dao/tx/tx.go
  service/apiserver/internal/logic/utils/converter.go
Labels: enhancement, ready for review

#164 prover: make sure the block sizes are sorted
  go.mod
  go.sum
  service/prover/prover/prover.go
Labels: bug, ready for review

#171 tree: commit, rollback different types of trees in parallel.
  core/blockchain.go
  go.mod
  go.sum
  service/witness/witness/witness.go
  tree/account_tree.go
  tree/liquidity_tree.go
  tree/nft_tree.go
  tree/util.go
Labels: ready for review

#155 core: add gas check for transactions
  core/blockchain.go
  core/executor/base_executor.go
  core/executor/executor.go
  core/statedb/chaindb.go
  core/statedb/statedb.go
  dao/dbcache/cache.go
  go.mod
  go.sum
  service/apiserver/internal/logic/transaction/getnextnoncelogic.go
  service/apiserver/internal/logic/transaction/sendtxlogic.go
Labels: enhancement, ready for review

#157 core, dao: refactor transaction
  core/block_processor.go
  core/blockchain.go
  core/executor/add_liquidity_executor.go
  core/executor/atomic_match_executor.go
  core/executor/base_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/create_pair_executor.go
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/executor.go
  core/executor/full_exit_executor.go
  core/executor/full_exit_nft_executor.go
  core/executor/mint_nft_executor.go
  core/executor/register_zns_executor.go
  core/executor/remove_liquidity_executor.go
  core/executor/swap_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/update_pair_rate_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/chaindb.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  dao/block/block.go
  dao/mempool/mempool.go
  dao/tx/fail_tx.go
  dao/tx/tx.go
  dao/tx/tx_detail.go
  dao/tx/tx_pool.go
  docs/api_reference.md
  docs/protocol.md
  docs/storage_layout.md
  service/apiserver/internal/handler/routes.go
  service/apiserver/internal/handler/transaction/getaccountpendingtxshandler.go
  service/apiserver/internal/handler/transaction/getpendingtxshandler.go
  service/apiserver/internal/logic/block/getblocklogic.go
  service/apiserver/internal/logic/block/getblockslogic.go
  service/apiserver/internal/logic/transaction/getaccountpendingtxslogic.go
  service/apiserver/internal/logic/transaction/getaccounttxslogic.go
  service/apiserver/internal/logic/transaction/getblocktxslogic.go
  service/apiserver/internal/logic/transaction/getnextnoncelogic.go
  service/apiserver/internal/logic/transaction/getpendingtxslogic.go
  service/apiserver/internal/logic/transaction/gettxlogic.go
  service/apiserver/internal/logic/transaction/gettxslogic.go
  service/apiserver/internal/logic/transaction/sendtxlogic.go
  service/apiserver/internal/logic/utils/converter.go
  service/apiserver/internal/svc/servicecontext.go
  service/apiserver/server.api
  service/apiserver/test/getaccountpendingtxs_test.go
  service/apiserver/test/getpendingtxs_test.go
  service/committer/committer/committer.go
  service/monitor/monitor/monitor.go
  service/monitor/monitor/monitor_generic_blocks.go
  service/monitor/monitor/monitor_priority_requests.go
  tools/dbinitializer/main.go
  types/code.go
  types/constant.go
Labels: enhancement, ready for review

#176 feat: add graceful shutdown to different components
  core/statedb/chaindb.go
  core/statedb/statedb.go
  dao/dbcache/cache.go
  dao/dbcache/redis_cache.go
  service/apiserver/internal/svc/servicecontext.go
  service/apiserver/server.go
  service/committer/committer.go
  service/committer/committer/committer.go
  service/monitor/monitor.go
  service/monitor/monitor/monitor.go
  service/prover/prover.go
  service/prover/prover/prover.go
  service/sender/sender.go
  service/sender/sender/sender.go
  service/witness/witness.go
  service/witness/witness/witness.go
Labels: enhancement, ready for review

#184 committer: fix tx status is not updated issue
  dao/block/block.go
  dao/tx/tx.go
  service/monitor/monitor/monitor.go
  service/monitor/monitor/monitor_generic_blocks.go
  types/code.go
Labels: bug, ready for review

#188 monitor: reduce duplicate codes
  service/monitor/monitor/monitor.go
  service/monitor/monitor/monitor_generic_blocks.go
  service/monitor/monitor/monitor_governance_blocks.go
Labels: ready for review

#187 statedb: refactor cache layer
  core/block_processor.go
  core/blockchain.go
  core/executor/add_liquidity_executor.go
  core/executor/atomic_match_executor.go
  core/executor/base_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/create_pair_executor.go
  core/executor/deposit_executor.go
  core/executor/deposit_nft_executor.go
  core/executor/full_exit_executor.go
  core/executor/full_exit_nft_executor.go
  core/executor/mint_nft_executor.go
  core/executor/register_zns_executor.go
  core/executor/remove_liquidity_executor.go
  core/executor/swap_executor.go
  core/executor/transfer_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/update_pair_rate_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  core/statedb/statedb.go
  go.mod
  service/apiserver/internal/logic/transaction/getnextnoncelogic.go
  service/apiserver/internal/logic/transaction/sendtxlogic.go
Labels: enhancement, ready for review

#192 monitor: clean history l1 synced blocks
  dao/l1syncedblock/l1_synced_block.go
  deploy-local.sh
  deployment/docker-compose/docker-compose.sh
  deployment/helm/local-value/values.yaml
  deployment/helm/zkbnb/.helmignore
  deployment/helm/zkbnb/Chart.yaml
  deployment/helm/zkbnb/templates/NOTES.txt
  deployment/helm/zkbnb/templates/_helpers.tpl
  deployment/helm/zkbnb/templates/configmap.yaml
  deployment/helm/zkbnb/templates/deployment.yaml
  deployment/helm/zkbnb/templates/hpa.yaml
  deployment/helm/zkbnb/templates/ingress.yaml
  deployment/helm/zkbnb/templates/service.yaml
  deployment/helm/zkbnb/templates/serviceaccount.yaml
  deployment/helm/zkbnb/templates/tests/test-connection.yaml
  deployment/helm/zkbnb/values.yaml
  service/monitor/config/config.go
  service/monitor/etc/config.yaml.example
  service/monitor/monitor.go
  service/monitor/monitor/clean_history_blocks.go
  service/monitor/monitor/monitor.go
Labels: enhancement, ready for review

#194 apiserver: add pending tx limit config
  deploy-local.sh
  deployment/docker-compose/docker-compose.sh
  deployment/helm/zkbnb/templates/configmap.yaml
  service/apiserver/etc/server-api.yaml.example
  service/apiserver/internal/config/config.go
  service/apiserver/internal/logic/transaction/sendtxlogic.go
  service/apiserver/test/suite_test.go
  types/code.go
Labels: ready for review

#199 refactor: update the dependency of eth-rpc repo
  common/chain/block_helper.go
  go.mod
  go.sum
  service/monitor/monitor/monitor_generic_blocks.go
  service/monitor/monitor/monitor_governance_blocks.go
  service/monitor/monitor/types.go
  service/sender/sender/sender.go
  service/sender/sender/types.go
Labels: ready for review

#197 refactor: reuse constant as much as possible
  common/prove/add_liquidity.go
  common/prove/atomic_match.go
  common/prove/cancel_offer.go
  common/prove/create_collection.go
  common/prove/create_pair.go
  common/prove/deposit.go
  common/prove/deposit_nft.go
  common/prove/fullexit.go
  common/prove/fullexit_nft.go
  common/prove/mint_nft.go
  common/prove/proof_keys.go
  common/prove/register_zns.go
  common/prove/remove_liquidity.go
  common/prove/swap.go
  common/prove/transfer.go
  common/prove/transfer_nft.go
  common/prove/types.go
  common/prove/update_pairrate.go
  common/prove/withdraw.go
  common/prove/withdraw_nft.go
  common/prove/witness_helper.go
  common/prove/witness_test.go
  core/executor/add_liquidity_executor.go
  core/executor/cancel_offer_executor.go
  core/executor/create_collection_executor.go
  core/executor/mint_nft_executor.go
  core/executor/remove_liquidity_executor.go
  core/executor/swap_executor.go
  core/executor/transfer_nft_executor.go
  core/executor/withdraw_executor.go
  core/executor/withdraw_nft_executor.go
  core/statedb/state_cache.go
  deploy-local.sh
  deploy-qa.sh
  deployment/docker-compose/docker-compose.sh
  deployment/helm/local-value/values.yaml
  deployment/helm/zkbnb/values.yaml
  deployment/tool/tool.sh
  go.mod
  go.sum
  service/apiserver/etc/server-api.yaml.example
  service/apiserver/internal/cache/mem_cache.go
  service/apiserver/internal/fetcher/price/fetcher.go
  service/apiserver/internal/logic/account/getaccountlogic.go
  service/apiserver/internal/logic/nft/getmaxofferidlogic.go
  service/apiserver/internal/logic/pair/getlpvaluelogic.go
  service/apiserver/internal/logic/pair/getswapamountlogic.go
  service/apiserver/internal/svc/servicecontext.go
  service/apiserver/test/suite_test.go
  service/prover/prover/prover.go
  service/witness/witness/witness.go
  tree/types.go
  types/tx.go
Labels: ready for review, refactor

#196 deployment: fix `make tools` naming conflict with folders
  Makefile
Labels: ready for review

#201 release: prepare for release v0.0.3
  go.mod
  go.sum
Labels: ready for review

#210 feat: add icon url for assets
  docs/api_reference.md
  service/apiserver/internal/logic/asset/getassetlogic.go
  service/apiserver/internal/logic/asset/getassetslogic.go
  service/apiserver/server.api
Labels: enhancement, ready for review

#208 fix deploy local script
  deploy-local.sh
Labels: bug, ready for review
